### ISSUE TITLE
Duplicate admins list in groups

### ISSUE THREAD

**Issue by FDeghy** [SergiX44/Nutgram#95]
Have bug in getChatAdministrators request
Repeat one admin ChatMember for all

Thanks.

**Comment by SergiX44** [comment]
Sorry, can you explain better what are you trying to do?
Please post some payloads/snippet.

**Comment by FDeghy** [comment]
`$g_admins = (array) $bot->getChatAdministrators($chat_id);
$o = '';
foreach ($g_admins as $key => $val){
    $o .= $val->user->first_name."\n";
}
$bot->sendMessage($o);`

I use getChatAdministrators to get all admins of group but it return a array that have just one admin ChatMember that it repeated.

for ex:
admin list:
1. User1
2. User2
3. User3

but it return:
1. User1
2. User1
3. User1

**Comment by SergiX44** [comment]
> ```
> $g_admins = (array) $bot->getChatAdministrators($chat_id);  
> $o = '';  
> foreach ($g_admins as $key => $val){  
>     $o .= $val->user->first_name."\n";  
> }  
> $bot->sendMessage($o);
> ```
> 
> I use getChatAdministrators to get all admins of group but it return a array that have just one admin ChatMember that it repeated.
> 
> for ex: admin list:
> 
> 1. User1
> 2. User2
> 3. User3
> 
> but it return:
> 
> 1. User1
> 2. User1
> 3. User1

Can you please try it with `"sergix44/nutgram": "dev-dev"` version in composer and see if happens again?

**Comment by FDeghy** [comment]
It's fixed on `"sergix44/nutgram": "dev-dev"` version
Thanks

**Comment by SergiX44** [comment]
Will be fixed in release 1.1.1
